name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Build the mg_traits Image
      run: |
        docker build -t ghcr.io/epereira/mg_traits:latest -f cont_env/Dockerfile .
        docker run ghcr.io/epereira/mg_traits:latest . . --help
        docker push ghcr.io/epereira/mg_traits:latest
      
      
