name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ghcr.io/epereira/mg_traits:latest -f cont_env/Dockerfile .
      run: docker run ghcr.io/epereira/mg_traits:latest . . --help
      run: docker push ghcr.io/epereira/mg_traits:latest
      
      
